### ISSUE TITLE
Bluesound app just stopped workin on HP2019

### ISSUE THREAD

**Issue by oddinge73** [roelofoomen/com.bluesound#16]
Hello.

After an update of HP2019 Bluesound app just stopped workin. I can get any comms. IP is same, port is 11000 as default, same for poll at 100. Do I need to change parameter, or is an update of app needed?

Best regards
Odd Inge

**Comment by roelofoomen** [comment]
The last version has fixed a lot of crashes, how does the app work for you now?

**Comment by oddinge73** [comment]
It works now, thank you
