### ISSUE TITLE
Can no longer connect to my speakers

### ISSUE THREAD

**Issue by joepwijers** [roelofoomen/com.bluesound#2]
I have been using the bluesound app on Homey for a while. Sometimes somehow the connections is lost (the device gets a red triangle badge, and when you click it, it say the device is not available). One solution I used in such situations is to remove the device and add it again.

But now I enter the IP and press the button to test the connection and I get Unknown Error, and it says to check if Homey and the device are in the same network.

They are in the same network. On my phone, also in that network, I can browse that IP to get the diagnostics page of the speaker. I can also get the status on port 11000 using this url http://192.168.178.44:11000/Status

Behavior is the same for my othe bluesound speakers.

So now I am stuck as I can no longer use the app.

Can you help me with this issue.

Thanks,
Joep
(English, Dutch)

**Comment by jghaanstra** [comment]
This seems to be a specific issue for your setup. Please continue the discussion in the support thread on the Athom community forum.
