### ISSUE TITLE
Relative volume

### ISSUE THREAD

**Issue by Skierffe** [roelofoomen/com.bluesound#3]
Set relative volume is only possible in three steps. -100%, 0% and +100%. It works the same in Android, IOS and desktop app. It should be possible to set the relative volume to any percentage as you can with 'set volume to'.

**Comment by jghaanstra** [comment]
Fixed with release 1.3.2. https://github.com/jghaanstra/com.bluesound/releases/tag/1.3.2

It's been submitted to the app store and is pending approval.
