### ISSUE TITLE
Bluesound Node N130 not found

### ISSUE THREAD

**Issue by barto74** [roelofoomen/com.bluesound#9]
I have added a Bluesound Node (the latest edition) to my setup. Trying to add it to Homey but nothing happens. I enter the IP address of the Homey, didn’t change the port number. Pressing ‘test connection’ doesn’t give any result. I’m just stuck in the screen. 
im happy to provide any needed information to solve this issue!

**Comment by jghaanstra** [comment]
I dont use Homey anymore and I'm looking for someone to take over development. You are better of posting this in the support forum to see if someone can help you. But you can start with testing this url: http://ipaddress:port/SyncStatus (replacing with the correct IP and port of your device.

**Comment by barto74** [comment]
Sad to hear you stopped developing! The link you provided gives a proper document with info. I'll go to the support forum.

**Comment by jghaanstra** [comment]
Could you post the result here.

**Comment by barto74** [comment]
After testing the URL, I tried adding the Bluesound to Homey and it worked. No clue what the issue was earlier. Thanks for responding!
